import type { CategoryId, Product } from "./types";

type GutterSys = "pvc" | "zn" | "al" | "cu";
type GutterPrices = {
  can: number;
  dis: number;
  sta: number;
  tes: number;
  ang: number;
  boc: number;
  gom: number;
  col: number;
  giu: number;
};

function gutterFamily(sys: GutterSys, sizeLabel: string, prices: GutterPrices): Product[] {
  const lin = (part: "can" | "dis", price: number): Product => ({
    id: `gro-${sys}-${part}`,
    category: "gronde",
    kind: "linear",
    sizeLabel,
    yieldPerUnit: 1,
    yieldUnit: "ml",
    defaultWaste: 8,
    unitPrice: price,
  });
  const pz = (part: string, price: number): Product => ({
    id: `gro-${sys}-${part}`,
    category: "gronde",
    kind: "count",
    sizeLabel: "pz",
    yieldPerUnit: 1,
    yieldUnit: "pz",
    defaultWaste: 5,
    unitPrice: price,
  });
  return [
    lin("can", prices.can),
    lin("dis", prices.dis),
    pz("sta", prices.sta),
    pz("tes", prices.tes),
    pz("ang", prices.ang),
    pz("boc", prices.boc),
    pz("gom", prices.gom),
    pz("col", prices.col),
    pz("giu", prices.giu),
  ];
}

export const PRODUCTS: Product[] = [
  // Tegole — pezzi/m² da listini laterizi italiani
  {
    id: "teg-mars",
    category: "tegole",
    kind: "count-area",
    sizeLabel: "41,5 × 26 cm",
    yieldPerUnit: 13.5,
    yieldUnit: "pz/m²",
    packSize: 240,
    packKind: "bancale",
    kgEach: 3.1,
    defaultWaste: 10,
    unitPrice: 1.15,
    areaSurface: "roof",
  },
  {
    id: "teg-port",
    category: "tegole",
    kind: "count-area",
    sizeLabel: "43,5 × 26 cm",
    yieldPerUnit: 12,
    yieldUnit: "pz/m²",
    packSize: 240,
    packKind: "bancale",
    kgEach: 3.5,
    defaultWaste: 10,
    unitPrice: 1.35,
    areaSurface: "roof",
  },
  {
    id: "teg-olan",
    category: "tegole",
    kind: "count-area",
    sizeLabel: "42 × 25 cm",
    yieldPerUnit: 14,
    yieldUnit: "pz/m²",
    packSize: 240,
    packKind: "bancale",
    kgEach: 2.8,
    defaultWaste: 10,
    unitPrice: 1.20,
    areaSurface: "roof",
  },
  {
    id: "teg-pian",
    category: "tegole",
    kind: "count-area",
    sizeLabel: "42 × 33 cm",
    yieldPerUnit: 10,
    yieldUnit: "pz/m²",
    packSize: 180,
    packKind: "bancale",
    kgEach: 4.2,
    defaultWaste: 10,
    unitPrice: 1.85,
    areaSurface: "roof",
  },

  // Coppi
  {
    id: "cop-4516",
    category: "coppi",
    kind: "count-area",
    sizeLabel: "45 × 16 cm",
    yieldPerUnit: 28,
    yieldUnit: "pz/m²",
    packSize: 200,
    packKind: "bancale",
    kgEach: 2.4,
    defaultWaste: 10,
    unitPrice: 1.10,
    areaSurface: "roof",
  },
  {
    id: "cop-4516c",
    category: "coppi",
    kind: "count-area",
    sizeLabel: "45 × 16 cm",
    yieldPerUnit: 14,
    yieldUnit: "pz/m²",
    packSize: 200,
    packKind: "bancale",
    kgEach: 2.4,
    defaultWaste: 10,
    unitPrice: 0.95,
    areaSurface: "roof",
  },
  {
    id: "cop-4016",
    category: "coppi",
    kind: "count-area",
    sizeLabel: "40 × 16 cm",
    yieldPerUnit: 32,
    yieldUnit: "pz/m²",
    packSize: 220,
    packKind: "bancale",
    kgEach: 2.1,
    defaultWaste: 10,
    unitPrice: 0.88,
    areaSurface: "roof",
  },

  // Guaine e membrane tetto — 1 m² di membrana al m² di falda
  {
    id: "gua-bit4",
    category: "guaine",
    kind: "count-area",
    sizeLabel: "rotolo 10 m² · 4 mm",
    yieldPerUnit: 1,
    yieldUnit: "pz/m²",
    packSize: 10,
    packKind: "rotolo",
    kgEach: 4.5,
    defaultWaste: 12,
    unitPrice: 8.50,
    areaSurface: "roof",
  },
  {
    id: "gua-ard",
    category: "guaine",
    kind: "count-area",
    sizeLabel: "rotolo 10 m² · 4 mm",
    yieldPerUnit: 1,
    yieldUnit: "pz/m²",
    packSize: 10,
    packKind: "rotolo",
    kgEach: 4.8,
    defaultWaste: 12,
    unitPrice: 9.80,
    areaSurface: "roof",
  },
  {
    id: "gua-auto",
    category: "guaine",
    kind: "count-area",
    sizeLabel: "rotolo 10 m²",
    yieldPerUnit: 1,
    yieldUnit: "pz/m²",
    packSize: 10,
    packKind: "rotolo",
    kgEach: 3.2,
    defaultWaste: 10,
    unitPrice: 11.50,
    areaSurface: "roof",
  },
  {
    id: "gua-pvc",
    category: "guaine",
    kind: "count-area",
    sizeLabel: "rotolo 15 m² · 1,5 mm",
    yieldPerUnit: 1,
    yieldUnit: "pz/m²",
    packSize: 15,
    packKind: "rotolo",
    kgEach: 1.8,
    defaultWaste: 10,
    unitPrice: 14.50,
    areaSurface: "roof",
  },
  {
    id: "gua-trasp",
    category: "guaine",
    kind: "count-area",
    sizeLabel: "rotolo 75 m²",
    yieldPerUnit: 1,
    yieldUnit: "pz/m²",
    packSize: 75,
    packKind: "rotolo",
    kgEach: 0.16,
    defaultWaste: 10,
    unitPrice: 2.80,
    areaSurface: "roof",
  },

  // Gronde — canale, discendente e accessori per sistema
  ...gutterFamily("pvc", "Ø 80 mm", {
    can: 4.80,
    dis: 5.20,
    sta: 1.80,
    tes: 2.40,
    ang: 4.50,
    boc: 6.80,
    gom: 3.20,
    col: 1.50,
    giu: 2.20,
  }),
  ...gutterFamily("zn", "Ø 80 mm", {
    can: 8.50,
    dis: 7.80,
    sta: 2.60,
    tes: 3.80,
    ang: 7.20,
    boc: 9.50,
    gom: 4.80,
    col: 2.20,
    giu: 3.40,
  }),
  ...gutterFamily("al", "Ø 80 mm", {
    can: 12.50,
    dis: 11.80,
    sta: 3.40,
    tes: 5.20,
    ang: 9.80,
    boc: 12.50,
    gom: 6.50,
    col: 2.80,
    giu: 4.60,
  }),
  ...gutterFamily("cu", "Ø 80 mm", {
    can: 38.0,
    dis: 42.0,
    sta: 8.50,
    tes: 12.0,
    ang: 22.0,
    boc: 28.0,
    gom: 16.0,
    col: 7.50,
    giu: 14.0,
  }),

  // Poroton — modulo 25 cm, ~16 pz/m²
  {
    id: "por-8",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "8 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 80,
    packKind: "bancale",
    kgEach: 6,
    defaultWaste: 5,
    unitPrice: 1.45,
    areaSurface: "wall",
  },
  {
    id: "por-12",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "12 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 60,
    packKind: "bancale",
    kgEach: 9,
    defaultWaste: 5,
    unitPrice: 1.95,
    areaSurface: "wall",
  },
  {
    id: "por-20",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "20 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 48,
    packKind: "bancale",
    kgEach: 13,
    defaultWaste: 5,
    unitPrice: 2.85,
    areaSurface: "wall",
  },
  {
    id: "por-25",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "25 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 40,
    packKind: "bancale",
    kgEach: 16,
    defaultWaste: 5,
    unitPrice: 3.45,
    areaSurface: "wall",
  },
  {
    id: "por-30",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "30 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 36,
    packKind: "bancale",
    kgEach: 19,
    defaultWaste: 5,
    unitPrice: 4.20,
    areaSurface: "wall",
  },
  {
    id: "por-35",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "35 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 32,
    packKind: "bancale",
    kgEach: 22,
    defaultWaste: 5,
    unitPrice: 4.90,
    areaSurface: "wall",
  },
  {
    id: "por-45",
    category: "poroton",
    kind: "count-area",
    sizeLabel: "45 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 24,
    packKind: "bancale",
    kgEach: 26,
    defaultWaste: 5,
    unitPrice: 6.40,
    areaSurface: "wall",
  },

  // Cemento — sacco 25 kg
  {
    id: "cem-325-cls",
    category: "cemento",
    kind: "count-volume",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 12,
    yieldUnit: "sacco/m³",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 5,
    unitPrice: 6.50,
  },
  {
    id: "cem-325-malta",
    category: "cemento",
    kind: "count-volume",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 10,
    yieldUnit: "sacco/m³",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 5,
    unitPrice: 6.50,
  },
  {
    id: "cem-425-cls",
    category: "cemento",
    kind: "count-volume",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 13,
    yieldUnit: "sacco/m³",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 5,
    unitPrice: 7.20,
  },
  {
    id: "cem-massetto",
    category: "cemento",
    kind: "count-area",
    sizeLabel: "sacco 25 kg · sp. 5 cm",
    yieldPerUnit: 0.8,
    yieldUnit: "sacco/m²",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 5,
    unitPrice: 7.00,
  },
  {
    id: "cem-predo",
    category: "cemento",
    kind: "count-volume",
    sizeLabel: "sacco 25 kg · 12 L",
    yieldPerUnit: 84,
    yieldUnit: "sacco/m³",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 5,
    unitPrice: 8.40,
  },

  // Foratini
  {
    id: "for-82525",
    category: "foratini",
    kind: "count-area",
    sizeLabel: "8 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 100,
    packKind: "bancale",
    kgEach: 5,
    defaultWaste: 5,
    unitPrice: 0.72,
    areaSurface: "wall",
  },
  {
    id: "for-82533",
    category: "foratini",
    kind: "count-area",
    sizeLabel: "8 × 25 × 33 cm",
    yieldPerUnit: 12,
    yieldUnit: "pz/m²",
    packSize: 80,
    packKind: "bancale",
    kgEach: 6,
    defaultWaste: 5,
    unitPrice: 0.88,
    areaSurface: "wall",
  },
  {
    id: "for-122525",
    category: "foratini",
    kind: "count-area",
    sizeLabel: "12 × 25 × 25 cm",
    yieldPerUnit: 16,
    yieldUnit: "pz/m²",
    packSize: 80,
    packKind: "bancale",
    kgEach: 8,
    defaultWaste: 5,
    unitPrice: 1.05,
    areaSurface: "wall",
  },
  {
    id: "for-121225",
    category: "foratini",
    kind: "count-area",
    sizeLabel: "12 × 12 × 25 cm",
    yieldPerUnit: 30,
    yieldUnit: "pz/m²",
    packSize: 200,
    packKind: "bancale",
    kgEach: 4.5,
    defaultWaste: 5,
    unitPrice: 0.52,
    areaSurface: "wall",
  },

  // Mattoni
  {
    id: "mat-uni",
    category: "mattoni",
    kind: "count-area",
    sizeLabel: "5,5 × 12 × 25 cm",
    yieldPerUnit: 56,
    yieldUnit: "pz/m²",
    packSize: 400,
    packKind: "bancale",
    kgEach: 3.4,
    defaultWaste: 5,
    unitPrice: 0.48,
    areaSurface: "wall",
  },
  {
    id: "mat-fav",
    category: "mattoni",
    kind: "count-area",
    sizeLabel: "5,5 × 12 × 25 cm",
    yieldPerUnit: 56,
    yieldUnit: "pz/m²",
    packSize: 400,
    packKind: "bancale",
    kgEach: 3.2,
    defaultWaste: 5,
    unitPrice: 0.92,
    areaSurface: "wall",
  },
  {
    id: "mat-for8",
    category: "mattoni",
    kind: "count-area",
    sizeLabel: "8 × 12 × 25 cm",
    yieldPerUnit: 40,
    yieldUnit: "pz/m²",
    packSize: 320,
    packKind: "bancale",
    kgEach: 2.8,
    defaultWaste: 5,
    unitPrice: 0.42,
    areaSurface: "wall",
  },
  {
    id: "mat-doppio",
    category: "mattoni",
    kind: "count-area",
    sizeLabel: "12 × 12 × 25 cm",
    yieldPerUnit: 30,
    yieldUnit: "pz/m²",
    packSize: 200,
    packKind: "bancale",
    kgEach: 5,
    defaultWaste: 5,
    unitPrice: 0.68,
    areaSurface: "wall",
  },

  // Legno lamellare — sezioni usuali, aste da 12 m in magazzino
  {
    id: "leg-0816",
    category: "legno",
    kind: "linear",
    sizeLabel: "8 × 16 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 8,
    sectionH: 16,
    defaultWaste: 5,
    unitPrice: 9.60,
  },
  {
    id: "leg-1020",
    category: "legno",
    kind: "linear",
    sizeLabel: "10 × 20 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 10,
    sectionH: 20,
    defaultWaste: 5,
    unitPrice: 14.50,
  },
  {
    id: "leg-1216",
    category: "legno",
    kind: "linear",
    sizeLabel: "12 × 16 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 12,
    sectionH: 16,
    defaultWaste: 5,
    unitPrice: 13.80,
  },
  {
    id: "leg-1224",
    category: "legno",
    kind: "linear",
    sizeLabel: "12 × 24 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 12,
    sectionH: 24,
    defaultWaste: 5,
    unitPrice: 20.50,
  },
  {
    id: "leg-1428",
    category: "legno",
    kind: "linear",
    sizeLabel: "14 × 28 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 14,
    sectionH: 28,
    defaultWaste: 5,
    unitPrice: 27.80,
  },
  {
    id: "leg-1632",
    category: "legno",
    kind: "linear",
    sizeLabel: "16 × 32 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 16,
    sectionH: 32,
    defaultWaste: 5,
    unitPrice: 36.50,
  },
  {
    id: "leg-2040",
    category: "legno",
    kind: "linear",
    sizeLabel: "20 × 40 cm",
    yieldPerUnit: 1,
    yieldUnit: "ml",
    sectionW: 20,
    sectionH: 40,
    defaultWaste: 5,
    unitPrice: 57.00,
  },

  // Isolanti
  {
    id: "iso-eps10",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "100 × 50 × 10 cm",
    yieldPerUnit: 2,
    yieldUnit: "pz/m²",
    packSize: 6,
    packKind: "bancale",
    defaultWaste: 8,
    unitPrice: 6.80,
    areaSurface: "wall",
  },
  {
    id: "iso-xps8",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "125 × 60 × 8 cm",
    yieldPerUnit: 1.34,
    yieldUnit: "pz/m²",
    packSize: 8,
    packKind: "bancale",
    defaultWaste: 8,
    unitPrice: 8.40,
    areaSurface: "wall",
  },
  {
    id: "iso-lana10",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "rotolo 10 cm",
    yieldPerUnit: 1.05,
    yieldUnit: "pz/m²",
    packSize: 12,
    packKind: "bancale",
    defaultWaste: 10,
    unitPrice: 7.20,
    areaSurface: "wall",
  },
  {
    id: "iso-tetto8",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "pannello 8 cm",
    yieldPerUnit: 1.05,
    yieldUnit: "pz/m²",
    packSize: 10,
    packKind: "bancale",
    defaultWaste: 8,
    unitPrice: 9.50,
    areaSurface: "roof",
  },
  {
    id: "iso-tetto12",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "pannello 12 cm",
    yieldPerUnit: 1.05,
    yieldUnit: "pz/m²",
    packSize: 8,
    packKind: "bancale",
    defaultWaste: 8,
    unitPrice: 13.20,
    areaSurface: "roof",
  },
  {
    id: "iso-pir10",
    category: "isolanti",
    kind: "count-area",
    sizeLabel: "PIR 10 cm",
    yieldPerUnit: 1.05,
    yieldUnit: "pz/m²",
    packSize: 10,
    packKind: "bancale",
    defaultWaste: 8,
    unitPrice: 16.80,
    areaSurface: "roof",
  },

  // Intonaci e malte
  {
    id: "int-civ",
    category: "intonaci",
    kind: "count-area",
    sizeLabel: "sacco 25 kg · 1,5 cm",
    yieldPerUnit: 0.85,
    yieldUnit: "sacco/m²",
    packSize: 48,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 7.80,
    areaSurface: "wall",
  },
  {
    id: "int-ras",
    category: "intonaci",
    kind: "count-area",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 0.28,
    yieldUnit: "sacco/m²",
    packSize: 48,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 12.50,
    areaSurface: "wall",
  },
  {
    id: "int-term",
    category: "intonaci",
    kind: "count-area",
    sizeLabel: "sacco 25 kg · 4 cm",
    yieldPerUnit: 1.15,
    yieldUnit: "sacco/m²",
    packSize: 40,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 14.80,
    areaSurface: "wall",
  },
  {
    id: "mal-m5",
    category: "intonaci",
    kind: "count-area",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 1.2,
    yieldUnit: "sacco/m²",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 6.20,
    areaSurface: "wall",
  },
  {
    id: "mal-m10",
    category: "intonaci",
    kind: "count-area",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 1.3,
    yieldUnit: "sacco/m²",
    packSize: 56,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 6.90,
    areaSurface: "wall",
  },

  // Colle e sigillanti
  {
    id: "col-c2",
    category: "sigillanti",
    kind: "count-area",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 0.35,
    yieldUnit: "sacco/m²",
    packSize: 48,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 14.20,
    areaSurface: "floor",
  },
  {
    id: "col-por",
    category: "sigillanti",
    kind: "count-area",
    sizeLabel: "sacco 25 kg",
    yieldPerUnit: 0.45,
    yieldUnit: "sacco/m²",
    packSize: 48,
    packKind: "bancale",
    bagKg: 25,
    kgEach: 25,
    defaultWaste: 8,
    unitPrice: 11.80,
    areaSurface: "wall",
  },
  {
    id: "sil-neu",
    category: "sigillanti",
    kind: "count-area",
    sizeLabel: "cartuccia 300 ml",
    yieldPerUnit: 0.125,
    yieldUnit: "pz/ml",
    packSize: 12,
    packKind: "cartone",
    defaultWaste: 15,
    unitPrice: 4.80,
    areaSurface: "joint",
  },
  {
    id: "sil-acr",
    category: "sigillanti",
    kind: "count-area",
    sizeLabel: "cartuccia 300 ml",
    yieldPerUnit: 0.12,
    yieldUnit: "pz/ml",
    packSize: 12,
    packKind: "cartone",
    defaultWaste: 15,
    unitPrice: 3.20,
    areaSurface: "joint",
  },
  {
    id: "sch-pu",
    category: "sigillanti",
    kind: "count-area",
    sizeLabel: "bombola 750 ml",
    yieldPerUnit: 0.08,
    yieldUnit: "pz/ml",
    packSize: 12,
    packKind: "cartone",
    defaultWaste: 15,
    unitPrice: 8.50,
    areaSurface: "joint",
  },
];

export const CATEGORY_ORDER: CategoryId[] = [
  "tegole",
  "coppi",
  "guaine",
  "gronde",
  "poroton",
  "cemento",
  "foratini",
  "mattoni",
  "legno",
  "isolanti",
  "intonaci",
  "sigillanti",
];

export const ROOF_COVERING_IDS = ["teg-mars", "teg-port", "teg-olan", "teg-pian", "cop-4516", "cop-4016"] as const;
export const ROOF_TIMBER_IDS = ["leg-0816", "leg-1020", "leg-1216", "leg-1224", "leg-1428", "leg-1632"] as const;
export const ROOF_MEMBRANE_IDS = ["gua-bit4", "gua-ard", "gua-auto", "gua-pvc", "gua-trasp"] as const;
export const ROOF_ISO_IDS = ["iso-tetto8", "iso-tetto12", "iso-pir10", "iso-lana10"] as const;
export const ROOF_GUTTER_IDS = ["gro-pvc", "gro-zn", "gro-al", "gro-cu"] as const;

export const GUTTER_PARTS = ["can", "dis", "sta", "tes", "ang", "boc", "gom", "col", "giu"] as const;

export function gutterPartId(system: string, part: (typeof GUTTER_PARTS)[number]): string {
  return `${system}-${part}`;
}

export function productsIn(category: CategoryId): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
