/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CantiereRouteImport } from './routes/cantiere'
import { Route as DigitaleRouteImport } from './routes/digitale'
import { Route as ImpreseRouteImport } from './routes/imprese'
import { Route as IndiceRouteImport } from './routes/indice'
import { Route as NaturaRouteImport } from './routes/natura'
import { Route as ParcoRouteImport } from './routes/parco'
import { Route as PortaleRouteImport } from './routes/portale'
import { Route as StorieRouteImport } from './routes/storie'
import { Route as ComuniIndexRouteImport } from './routes/comuni/index'
import { Route as ComuniSlugRouteImport } from './routes/comuni/$slug'
import { Route as DigitaleIndexRouteImport } from './routes/digitale.index'
import { Route as DigitaleStudioRouteImport } from './routes/digitale.studio'
import { Route as DigitaleTerritorioRouteImport } from './routes/digitale.territorio'
import { Route as EsperienzeIndexRouteImport } from './routes/esperienze/index'
import { Route as EsperienzeCalendarioRouteImport } from './routes/esperienze/calendario'
import { Route as EsperienzePlannerRouteImport } from './routes/esperienze/planner'
import { Route as EsperienzeTimelineRouteImport } from './routes/esperienze/timeline'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabAlberiRouteImport } from './routes/lab/alberi'
import { Route as LabAtlanteRouteImport } from './routes/lab/atlante'
import { Route as LabBiosferaRouteImport } from './routes/lab/biosfera'
import { Route as LabDroneRouteImport } from './routes/lab/drone'
import { Route as LabFaggetaRouteImport } from './routes/lab/faggeta'
import { Route as LabLegnoRouteImport } from './routes/lab/legno'
import { Route as LabParcoRouteImport } from './routes/lab/parco'
import { Route as LabSentieriRouteImport } from './routes/lab/sentieri'
import { Route as LabTramaRouteImport } from './routes/lab/trama'
import { Route as LabVoloRouteImport } from './routes/lab/volo'
import { Route as SentieriIndexRouteImport } from './routes/sentieri/index'
import { Route as SentieriSlugRouteImport } from './routes/sentieri/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CantiereRoute = CantiereRouteImport.update({
  id: '/cantiere',
  path: '/cantiere',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitaleRoute = DigitaleRouteImport.update({
  id: '/digitale',
  path: '/digitale',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpreseRoute = ImpreseRouteImport.update({
  id: '/imprese',
  path: '/imprese',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceRoute = IndiceRouteImport.update({
  id: '/indice',
  path: '/indice',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturaRoute = NaturaRouteImport.update({
  id: '/natura',
  path: '/natura',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoRoute = ParcoRouteImport.update({
  id: '/parco',
  path: '/parco',
  getParentRoute: () => rootRouteImport,
} as any)
const PortaleRoute = PortaleRouteImport.update({
  id: '/portale',
  path: '/portale',
  getParentRoute: () => rootRouteImport,
} as any)
const StorieRoute = StorieRouteImport.update({
  id: '/storie',
  path: '/storie',
  getParentRoute: () => rootRouteImport,
} as any)
const ComuniIndexRoute = ComuniIndexRouteImport.update({
  id: '/comuni/',
  path: '/comuni/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComuniSlugRoute = ComuniSlugRouteImport.update({
  id: '/comuni/$slug',
  path: '/comuni/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitaleIndexRoute = DigitaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DigitaleRoute,
} as any)
const DigitaleStudioRoute = DigitaleStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DigitaleRoute,
} as any)
const DigitaleTerritorioRoute = DigitaleTerritorioRouteImport.update({
  id: '/territorio',
  path: '/territorio',
  getParentRoute: () => DigitaleRoute,
} as any)
const EsperienzeIndexRoute = EsperienzeIndexRouteImport.update({
  id: '/esperienze/',
  path: '/esperienze/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperienzeCalendarioRoute = EsperienzeCalendarioRouteImport.update({
  id: '/esperienze/calendario',
  path: '/esperienze/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperienzePlannerRoute = EsperienzePlannerRouteImport.update({
  id: '/esperienze/planner',
  path: '/esperienze/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperienzeTimelineRoute = EsperienzeTimelineRouteImport.update({
  id: '/esperienze/timeline',
  path: '/esperienze/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAlberiRoute = LabAlberiRouteImport.update({
  id: '/lab/alberi',
  path: '/lab/alberi',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAtlanteRoute = LabAtlanteRouteImport.update({
  id: '/lab/atlante',
  path: '/lab/atlante',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBiosferaRoute = LabBiosferaRouteImport.update({
  id: '/lab/biosfera',
  path: '/lab/biosfera',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDroneRoute = LabDroneRouteImport.update({
  id: '/lab/drone',
  path: '/lab/drone',
  getParentRoute: () => rootRouteImport,
} as any)
const LabFaggetaRoute = LabFaggetaRouteImport.update({
  id: '/lab/faggeta',
  path: '/lab/faggeta',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLegnoRoute = LabLegnoRouteImport.update({
  id: '/lab/legno',
  path: '/lab/legno',
  getParentRoute: () => rootRouteImport,
} as any)
const LabParcoRoute = LabParcoRouteImport.update({
  id: '/lab/parco',
  path: '/lab/parco',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSentieriRoute = LabSentieriRouteImport.update({
  id: '/lab/sentieri',
  path: '/lab/sentieri',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTramaRoute = LabTramaRouteImport.update({
  id: '/lab/trama',
  path: '/lab/trama',
  getParentRoute: () => rootRouteImport,
} as any)
const LabVoloRoute = LabVoloRouteImport.update({
  id: '/lab/volo',
  path: '/lab/volo',
  getParentRoute: () => rootRouteImport,
} as any)
const SentieriIndexRoute = SentieriIndexRouteImport.update({
  id: '/sentieri/',
  path: '/sentieri/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentieriSlugRoute = SentieriSlugRouteImport.update({
  id: '/sentieri/$slug',
  path: '/sentieri/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cantiere': typeof CantiereRoute
  '/digitale': typeof DigitaleRouteWithChildren
  '/imprese': typeof ImpreseRoute
  '/indice': typeof IndiceRoute
  '/natura': typeof NaturaRoute
  '/parco': typeof ParcoRoute
  '/portale': typeof PortaleRoute
  '/storie': typeof StorieRoute
  '/comuni/$slug': typeof ComuniSlugRoute
  '/digitale/studio': typeof DigitaleStudioRoute
  '/digitale/territorio': typeof DigitaleTerritorioRoute
  '/esperienze/calendario': typeof EsperienzeCalendarioRoute
  '/esperienze/planner': typeof EsperienzePlannerRoute
  '/esperienze/timeline': typeof EsperienzeTimelineRoute
  '/lab/alberi': typeof LabAlberiRoute
  '/lab/atlante': typeof LabAtlanteRoute
  '/lab/biosfera': typeof LabBiosferaRoute
  '/lab/drone': typeof LabDroneRoute
  '/lab/faggeta': typeof LabFaggetaRoute
  '/lab/legno': typeof LabLegnoRoute
  '/lab/parco': typeof LabParcoRoute
  '/lab/sentieri': typeof LabSentieriRoute
  '/lab/trama': typeof LabTramaRoute
  '/lab/volo': typeof LabVoloRoute
  '/sentieri/$slug': typeof SentieriSlugRoute
  '/comuni/': typeof ComuniIndexRoute
  '/digitale/': typeof DigitaleIndexRoute
  '/esperienze/': typeof EsperienzeIndexRoute
  '/lab/': typeof LabIndexRoute
  '/sentieri/': typeof SentieriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cantiere': typeof CantiereRoute
  '/imprese': typeof ImpreseRoute
  '/indice': typeof IndiceRoute
  '/natura': typeof NaturaRoute
  '/parco': typeof ParcoRoute
  '/portale': typeof PortaleRoute
  '/storie': typeof StorieRoute
  '/comuni/$slug': typeof ComuniSlugRoute
  '/digitale/studio': typeof DigitaleStudioRoute
  '/digitale/territorio': typeof DigitaleTerritorioRoute
  '/esperienze/calendario': typeof EsperienzeCalendarioRoute
  '/esperienze/planner': typeof EsperienzePlannerRoute
  '/esperienze/timeline': typeof EsperienzeTimelineRoute
  '/lab/alberi': typeof LabAlberiRoute
  '/lab/atlante': typeof LabAtlanteRoute
  '/lab/biosfera': typeof LabBiosferaRoute
  '/lab/drone': typeof LabDroneRoute
  '/lab/faggeta': typeof LabFaggetaRoute
  '/lab/legno': typeof LabLegnoRoute
  '/lab/parco': typeof LabParcoRoute
  '/lab/sentieri': typeof LabSentieriRoute
  '/lab/trama': typeof LabTramaRoute
  '/lab/volo': typeof LabVoloRoute
  '/sentieri/$slug': typeof SentieriSlugRoute
  '/comuni': typeof ComuniIndexRoute
  '/digitale': typeof DigitaleIndexRoute
  '/esperienze': typeof EsperienzeIndexRoute
  '/lab': typeof LabIndexRoute
  '/sentieri': typeof SentieriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cantiere': typeof CantiereRoute
  '/digitale': typeof DigitaleRouteWithChildren
  '/imprese': typeof ImpreseRoute
  '/indice': typeof IndiceRoute
  '/natura': typeof NaturaRoute
  '/parco': typeof ParcoRoute
  '/portale': typeof PortaleRoute
  '/storie': typeof StorieRoute
  '/comuni/$slug': typeof ComuniSlugRoute
  '/digitale/studio': typeof DigitaleStudioRoute
  '/digitale/territorio': typeof DigitaleTerritorioRoute
  '/esperienze/calendario': typeof EsperienzeCalendarioRoute
  '/esperienze/planner': typeof EsperienzePlannerRoute
  '/esperienze/timeline': typeof EsperienzeTimelineRoute
  '/lab/alberi': typeof LabAlberiRoute
  '/lab/atlante': typeof LabAtlanteRoute
  '/lab/biosfera': typeof LabBiosferaRoute
  '/lab/drone': typeof LabDroneRoute
  '/lab/faggeta': typeof LabFaggetaRoute
  '/lab/legno': typeof LabLegnoRoute
  '/lab/parco': typeof LabParcoRoute
  '/lab/sentieri': typeof LabSentieriRoute
  '/lab/trama': typeof LabTramaRoute
  '/lab/volo': typeof LabVoloRoute
  '/sentieri/$slug': typeof SentieriSlugRoute
  '/comuni/': typeof ComuniIndexRoute
  '/digitale/': typeof DigitaleIndexRoute
  '/esperienze/': typeof EsperienzeIndexRoute
  '/lab/': typeof LabIndexRoute
  '/sentieri/': typeof SentieriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/cantiere'
    | '/digitale'
    | '/imprese'
    | '/indice'
    | '/natura'
    | '/parco'
    | '/portale'
    | '/storie'
    | '/comuni/$slug'
    | '/digitale/studio'
    | '/digitale/territorio'
    | '/esperienze/calendario'
    | '/esperienze/planner'
    | '/esperienze/timeline'
    | '/lab/alberi'
    | '/lab/atlante'
    | '/lab/biosfera'
    | '/lab/drone'
    | '/lab/faggeta'
    | '/lab/legno'
    | '/lab/parco'
    | '/lab/sentieri'
    | '/lab/trama'
    | '/lab/volo'
    | '/sentieri/$slug'
    | '/comuni/'
    | '/digitale/'
    | '/esperienze/'
    | '/lab/'
    | '/sentieri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/cantiere'
    | '/imprese'
    | '/indice'
    | '/natura'
    | '/parco'
    | '/portale'
    | '/storie'
    | '/comuni/$slug'
    | '/digitale/studio'
    | '/digitale/territorio'
    | '/esperienze/calendario'
    | '/esperienze/planner'
    | '/esperienze/timeline'
    | '/lab/alberi'
    | '/lab/atlante'
    | '/lab/biosfera'
    | '/lab/drone'
    | '/lab/faggeta'
    | '/lab/legno'
    | '/lab/parco'
    | '/lab/sentieri'
    | '/lab/trama'
    | '/lab/volo'
    | '/sentieri/$slug'
    | '/comuni'
    | '/digitale'
    | '/esperienze'
    | '/lab'
    | '/sentieri'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/cantiere'
    | '/digitale'
    | '/imprese'
    | '/indice'
    | '/natura'
    | '/parco'
    | '/portale'
    | '/storie'
    | '/comuni/$slug'
    | '/digitale/studio'
    | '/digitale/territorio'
    | '/esperienze/calendario'
    | '/esperienze/planner'
    | '/esperienze/timeline'
    | '/lab/alberi'
    | '/lab/atlante'
    | '/lab/biosfera'
    | '/lab/drone'
    | '/lab/faggeta'
    | '/lab/legno'
    | '/lab/parco'
    | '/lab/sentieri'
    | '/lab/trama'
    | '/lab/volo'
    | '/sentieri/$slug'
    | '/comuni/'
    | '/digitale/'
    | '/esperienze/'
    | '/lab/'
    | '/sentieri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CantiereRoute: typeof CantiereRoute
  DigitaleRoute: typeof DigitaleRouteWithChildren
  ImpreseRoute: typeof ImpreseRoute
  IndiceRoute: typeof IndiceRoute
  NaturaRoute: typeof NaturaRoute
  ParcoRoute: typeof ParcoRoute
  PortaleRoute: typeof PortaleRoute
  StorieRoute: typeof StorieRoute
  ComuniSlugRoute: typeof ComuniSlugRoute
  EsperienzeCalendarioRoute: typeof EsperienzeCalendarioRoute
  EsperienzePlannerRoute: typeof EsperienzePlannerRoute
  EsperienzeTimelineRoute: typeof EsperienzeTimelineRoute
  LabAlberiRoute: typeof LabAlberiRoute
  LabAtlanteRoute: typeof LabAtlanteRoute
  LabBiosferaRoute: typeof LabBiosferaRoute
  LabDroneRoute: typeof LabDroneRoute
  LabFaggetaRoute: typeof LabFaggetaRoute
  LabLegnoRoute: typeof LabLegnoRoute
  LabParcoRoute: typeof LabParcoRoute
  LabSentieriRoute: typeof LabSentieriRoute
  LabTramaRoute: typeof LabTramaRoute
  LabVoloRoute: typeof LabVoloRoute
  SentieriSlugRoute: typeof SentieriSlugRoute
  ComuniIndexRoute: typeof ComuniIndexRoute
  EsperienzeIndexRoute: typeof EsperienzeIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  SentieriIndexRoute: typeof SentieriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantiere': {
      id: '/cantiere'
      path: '/cantiere'
      fullPath: '/cantiere'
      preLoaderRoute: typeof CantiereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitale': {
      id: '/digitale'
      path: '/digitale'
      fullPath: '/digitale'
      preLoaderRoute: typeof DigitaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprese': {
      id: '/imprese'
      path: '/imprese'
      fullPath: '/imprese'
      preLoaderRoute: typeof ImpreseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice': {
      id: '/indice'
      path: '/indice'
      fullPath: '/indice'
      preLoaderRoute: typeof IndiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natura': {
      id: '/natura'
      path: '/natura'
      fullPath: '/natura'
      preLoaderRoute: typeof NaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parco': {
      id: '/parco'
      path: '/parco'
      fullPath: '/parco'
      preLoaderRoute: typeof ParcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portale': {
      id: '/portale'
      path: '/portale'
      fullPath: '/portale'
      preLoaderRoute: typeof PortaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storie': {
      id: '/storie'
      path: '/storie'
      fullPath: '/storie'
      preLoaderRoute: typeof StorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comuni/': {
      id: '/comuni/'
      path: '/comuni'
      fullPath: '/comuni/'
      preLoaderRoute: typeof ComuniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comuni/$slug': {
      id: '/comuni/$slug'
      path: '/comuni/$slug'
      fullPath: '/comuni/$slug'
      preLoaderRoute: typeof ComuniSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitale/': {
      id: '/digitale/'
      path: '/'
      fullPath: '/digitale/'
      preLoaderRoute: typeof DigitaleIndexRouteImport
      parentRoute: typeof DigitaleRoute
    }
    '/digitale/studio': {
      id: '/digitale/studio'
      path: '/studio'
      fullPath: '/digitale/studio'
      preLoaderRoute: typeof DigitaleStudioRouteImport
      parentRoute: typeof DigitaleRoute
    }
    '/digitale/territorio': {
      id: '/digitale/territorio'
      path: '/territorio'
      fullPath: '/digitale/territorio'
      preLoaderRoute: typeof DigitaleTerritorioRouteImport
      parentRoute: typeof DigitaleRoute
    }
    '/esperienze/': {
      id: '/esperienze/'
      path: '/esperienze'
      fullPath: '/esperienze/'
      preLoaderRoute: typeof EsperienzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperienze/calendario': {
      id: '/esperienze/calendario'
      path: '/esperienze/calendario'
      fullPath: '/esperienze/calendario'
      preLoaderRoute: typeof EsperienzeCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperienze/planner': {
      id: '/esperienze/planner'
      path: '/esperienze/planner'
      fullPath: '/esperienze/planner'
      preLoaderRoute: typeof EsperienzePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperienze/timeline': {
      id: '/esperienze/timeline'
      path: '/esperienze/timeline'
      fullPath: '/esperienze/timeline'
      preLoaderRoute: typeof EsperienzeTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/alberi': {
      id: '/lab/alberi'
      path: '/lab/alberi'
      fullPath: '/lab/alberi'
      preLoaderRoute: typeof LabAlberiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/atlante': {
      id: '/lab/atlante'
      path: '/lab/atlante'
      fullPath: '/lab/atlante'
      preLoaderRoute: typeof LabAtlanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/biosfera': {
      id: '/lab/biosfera'
      path: '/lab/biosfera'
      fullPath: '/lab/biosfera'
      preLoaderRoute: typeof LabBiosferaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/drone': {
      id: '/lab/drone'
      path: '/lab/drone'
      fullPath: '/lab/drone'
      preLoaderRoute: typeof LabDroneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/faggeta': {
      id: '/lab/faggeta'
      path: '/lab/faggeta'
      fullPath: '/lab/faggeta'
      preLoaderRoute: typeof LabFaggetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/legno': {
      id: '/lab/legno'
      path: '/lab/legno'
      fullPath: '/lab/legno'
      preLoaderRoute: typeof LabLegnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/parco': {
      id: '/lab/parco'
      path: '/lab/parco'
      fullPath: '/lab/parco'
      preLoaderRoute: typeof LabParcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/sentieri': {
      id: '/lab/sentieri'
      path: '/lab/sentieri'
      fullPath: '/lab/sentieri'
      preLoaderRoute: typeof LabSentieriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/trama': {
      id: '/lab/trama'
      path: '/lab/trama'
      fullPath: '/lab/trama'
      preLoaderRoute: typeof LabTramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/volo': {
      id: '/lab/volo'
      path: '/lab/volo'
      fullPath: '/lab/volo'
      preLoaderRoute: typeof LabVoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentieri/': {
      id: '/sentieri/'
      path: '/sentieri'
      fullPath: '/sentieri/'
      preLoaderRoute: typeof SentieriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentieri/$slug': {
      id: '/sentieri/$slug'
      path: '/sentieri/$slug'
      fullPath: '/sentieri/$slug'
      preLoaderRoute: typeof SentieriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DigitaleRouteChildren {
  DigitaleStudioRoute: typeof DigitaleStudioRoute
  DigitaleTerritorioRoute: typeof DigitaleTerritorioRoute
  DigitaleIndexRoute: typeof DigitaleIndexRoute
}

const DigitaleRouteChildren: DigitaleRouteChildren = {
  DigitaleStudioRoute: DigitaleStudioRoute,
  DigitaleTerritorioRoute: DigitaleTerritorioRoute,
  DigitaleIndexRoute: DigitaleIndexRoute,
}

const DigitaleRouteWithChildren = DigitaleRoute._addFileChildren(
  DigitaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CantiereRoute: CantiereRoute,
  DigitaleRoute: DigitaleRouteWithChildren,
  ImpreseRoute: ImpreseRoute,
  IndiceRoute: IndiceRoute,
  NaturaRoute: NaturaRoute,
  ParcoRoute: ParcoRoute,
  PortaleRoute: PortaleRoute,
  StorieRoute: StorieRoute,
  ComuniSlugRoute: ComuniSlugRoute,
  EsperienzeCalendarioRoute: EsperienzeCalendarioRoute,
  EsperienzePlannerRoute: EsperienzePlannerRoute,
  EsperienzeTimelineRoute: EsperienzeTimelineRoute,
  LabAlberiRoute: LabAlberiRoute,
  LabAtlanteRoute: LabAtlanteRoute,
  LabBiosferaRoute: LabBiosferaRoute,
  LabDroneRoute: LabDroneRoute,
  LabFaggetaRoute: LabFaggetaRoute,
  LabLegnoRoute: LabLegnoRoute,
  LabParcoRoute: LabParcoRoute,
  LabSentieriRoute: LabSentieriRoute,
  LabTramaRoute: LabTramaRoute,
  LabVoloRoute: LabVoloRoute,
  SentieriSlugRoute: SentieriSlugRoute,
  ComuniIndexRoute: ComuniIndexRoute,
  EsperienzeIndexRoute: EsperienzeIndexRoute,
  LabIndexRoute: LabIndexRoute,
  SentieriIndexRoute: SentieriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
